name: mtms_mri
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pillow=10.1.0
  - ipython=8.18.1
  - matplotlib=3.8.2
  - pandas=2.1.4
  - scipy=1.11.4
  - seaborn=0.13.0
  - h5py=3.10.0
  - python-dotenv=1.0.0
  - pip
